### ISSUE TITLE
Missing build.xml

### ISSUE THREAD

**Issue by Buzzroid** [crystax/android-samples-opengl#1]
The android build requires build.xml, but there is no such file.
Thanks.

**Comment by dmsck** [comment]
The `build.xml` is auto-generated. If you follow [instruction](https://github.com/crystax/android-samples-opengl/blob/master/README.md), it will be automatically generated.

**Comment by Buzzroid** [comment]
I shoud have run "make run", instead of just "make".
Sorry for bothering you.

Thank you very much for developing and sharing the greate CrystaX.

James

2016-02-10 23:06 GMT+09:00 Dmitry Moskalchuk notifications@github.com:
