### ISSUE TITLE
Android build failed (personality_v0)

### ISSUE THREAD

**Issue by kloned** [crystax/android-samples-opengl#2]
Hi,
Tried to build for OSX 10.11 (El Capitan), Android 21, crystax-ndk-10.3.1 (64-bit)
By running "make run", ended up with:
`[armeabi-v7a] SharedLibrary  : libapp-native.so
/opt/android/crystax-ndk-10.3.1/toolchains/llvm-3.7/prebuilt/darwin-x86_64/bin/clang++ -Wl,-soname,libapp-native.so -shared --sysroot=/opt/android/crystax-ndk-10.3.1/platforms/android-21/arch-arm ./obj/local/armeabi-v7a/objs/app-native/engine.o ./obj/local/armeabi-v7a/objs/app-native/main.o ./obj/local/armeabi-v7a/objs/app-native/platform.o ./obj/local/armeabi-v7a/objs/app-native/__/__/common/AppController.o ./obj/local/armeabi-v7a/libandroid_native_app_glue.a ./obj/local/armeabi-v7a/liblegacy.a -lgcc ./obj/local/armeabi-v7a/libgnustl_shared.so ./obj/local/armeabi-v7a/libFoundation.so ./obj/local/armeabi-v7a/libCoreVideo.so ./obj/local/armeabi-v7a/libCoreText.so ./obj/local/armeabi-v7a/libCoreData.so ./obj/local/armeabi-v7a/libCoreGraphics.so ./obj/local/armeabi-v7a/libCoreFoundation.so ./obj/local/armeabi-v7a/libCFNetwork.so ./obj/local/armeabi-v7a/libCoreServices.so ./obj/local/armeabi-v7a/libobjc.so  -gcc-toolchain /opt/android/crystax-ndk-10.3.1/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -no-canonical-prefixes -target armv7-none-linux-androideabi -Wl,--fix-cortex-a8  -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -mthumb -fobjc-arc  -L/opt/android/crystax-ndk-10.3.1/platforms/android-21/arch-arm/usr/lib -llog -landroid -lEGL -lGLESv2 -llog /opt/android/crystax-ndk-10.3.1/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -llog -lGLESv2 -L/opt/android/crystax-ndk-10.3.1/sources/crystax/empty /opt/android/crystax-ndk-10.3.1/sources/crystax/libs/armeabi-v7a/thumb/libcrystax.so -lc -o ./obj/local/armeabi-v7a/libapp-native.so
./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__initWithAndroidApp_+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__dealloc+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__setupGL+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
./obj/local/armeabi-v7a/objs/app-native/engine.o(.ARM.extab.text._i_Engine__tearDownGL+0x0): error: undefined reference to '__gnustep_objcxx_personality_v0'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [obj/local/armeabi-v7a/libapp-native.so] Error 1
make[1]: Leaving directory`/Users/mart/android-samples-opengl/android'
make: **\* [native] Error 2`

**Comment by dmsck** [comment]
I guess you're using 10.3.1. In this case – yes, there was bug with Objective-C++ code (i.e. code where both Objective-C and C++ were combined in single translation unit). Here it is: https://tracker.crystax.net/issues/1082. This bug was fixed some time ago, so this sample was updated to reflect that. However, that fix was not yet included to the public release.

So you have two options:
- Revert last commit and build everything with CrystaX NDK 10.3.1
- Or download latest daily build from https://dl.crystax.net/builds/ and use it instead of CrystaX NDK 10.3.1. This way everything will work with this repository "as is".

**Comment by kloned** [comment]
I've opted for your second suggestion and it works
Thank you!
